### PR TITLE
Fixed documentation typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./zlib,./freetype263 -L aline,ba,inout,lightyear,lightyears,lod,msdos,nd,ot,technic`

### CODE REVIEW

**Comment by luzpaz** [comment]
any progress on this?

**Comment by sbaer** [comment]
This specific PR is not going to me merged directly into opennurbs as it contains too many changes for me to comfortably accept everything. Some of the spelling errors have been integrated into our internal opennurbs and will show up here when we publish an update to the open source version.

Thanks, this has been helpful to find and fix these errors.

**Comment by luzpaz** [comment]
Thanks for the update. Yea, that makes sense it's pretty enormous. Cheers

**Comment by luzpaz** [comment]
Any update?

**Comment by sbaer** [comment]
Sorry, I accidentally closed this. I'm currently in the process of running codespell on the internal source

**Comment by sbaer** [comment]
Closing PR. I ran codespell on the opennurbs header files and published the changes in this PR
https://github.com/mcneel/opennurbs/pull/50

These changes are now in the `8.x` branch of opennurbs and will also show up when we publish the next version of the Rhino C++ SDK for Rhino 8.

Thanks for telling me about codespell; it's a great tool

**Pull request closed without merging**
