### PR TITLE
Add gnu compiler support

### PR DESCRIPTION
**Pull request by elifri**
Hey dear opennurbs developer,

thank you for your effort. As suggested in the forum[1], I put necessary changes to support gcc in linux in a fork. 
Thanks,
Elisa

[1] https://discourse.mcneel.com/t/patches-for-opennurbs-6-under-gcc-5-2-in-linux/72204

### CODE REVIEW

**Comment by jesterKing** [comment]
I think @dalelear needs to look at least at commits
01e4074 and 
bc54286, but otherwise seems ok.

**Comment by fraguada** [comment]
@jesterKing, added @dalelear as reviewer 😉

**Comment by sbaer** [comment]
I’m confused. This PR is trying to merge into my temporary branch that I thought @jesterKing already tuned up to work on gcc

**Comment by sbaer** [comment]
@elifri what error were you getting that forced you to change the WindowsLCID function name? We can’t really change the name in this way as it would break binary compatibility on Windows and it also doesn’t follow the style used for other function names. I also find it strange that this compiles on clang and visual c++ without errors

**Comment by elifri** [comment]
@sbaer 
I made a small snipplet that reproduces the error, see https://godbolt.org/z/F5CEnO. So, I used gcc-5.2 to compile opennurbs. All gcc-versions >6 do compile the code with the name collision just fine.
jesterKing patched the code to work under linux, but he used clang.

**Comment by Mathias-Fuchs** [comment]
What are the latest news on this?
I'm eagerly trying to compile opennurbs on linux with gcc too and it would be great to know the "official" McNeel status of these efforts. I'm also certain lots of folks would appreciate that as well. If possible, a further hint on how to go on and compile the 3dmio on top of that opennurbs would be really great. (as in https://discourse.mcneel.com/t/compiling-the-3dmiotoolkit-under-linux/32271). Thanks!

**Comment by jesterKing** [comment]
I have been compiling using Clang on my Linux box. I'll have to check if GCC still works - I have found GCC cumbersome with OpenNURBS, so I have kinda ignored that path

**Comment by Mathias-Fuchs** [comment]
Hello Nathan,

thanks for the answer. Well, I'm willing to give clang a try but some
modifications still seem to be necessary.
I'm using the newest temp_fix_for_py-rebase branch of opennurbs.
So far, I've found out that in the makefile,
- I set CC = clang and CCC = clang
- I have to add -DON_LITTLE_ENDIAN to the flags
- I guess I have to tell to use C++17?
- I have to make sure that the warning about unkown sizeof(wchar_t) doesn't
appear
etc. etc.
but what else? There are more tweaks necessary and I guess someone must
know about them.
Also, is the rhino3dmio toolkit expected to work out of the box with the
shared object libopennurbs.so built by clang or will there be more wizardry
needed?

Thanks!


https://mathiasfuchs.de

**Comment by pearswj** [comment]
Hi @elifri, sorry we’ve been so slow with this. I’ve now updated the `master` branch with recent changes from @jesterKing to add support for compiling with clang on Linux.

I had a go at re-applying your changes from 375346e and bc54286 (I think we’ll have to forgo GCC 5.x support for now, so I skipped 01e4074); see the [elifri-gcc](https://github.com/mcneel/opennurbs/tree/elifri-gcc) branch. Feels like it's close to working, but C++ is not my forte. I've asked @jesterKing to take a look too but if you have any suggestions, I'm all ears!

**Pull request closed without merging**
