### PR TITLE
RH-83540 Fix the crash

### PR DESCRIPTION
**Pull request by zhuda**
https://mcneel.myjetbrains.com/youtrack/issue/RH-83540 
Verified with this change, the crash issue is gone.

### CODE REVIEW

**Comment by sseelmann** [comment]
Hi, was this fix applied? I don't see it, neither in the current [mcneel:8.x](https://github.com/mcneel/opennurbs/tree/8.x) branch, nor the latest release [v8.13.24317.13001](https://github.com/mcneel/opennurbs/releases/tag/v8.13.24317.13001).

**Comment by dalefugier** [comment]
This remains an open issue.

https://mcneel.myjetbrains.com/youtrack/issue/RH-83540

**Comment by sseelmann** [comment]
Do you consider that bug to be a severe security issue? A heap corruption might in principle lead to arbitrary code execution, correct?

**Comment by dalefugier** [comment]
@sseelmann - the issue concerns reading of _some_ Rhino 2.0-formatted .3dm files. Not V2 files exhibit this behavior. I cannot address the heap corruption/code execution question, sorry.

**Pull request closed without merging**
